## Questão 1

Crie dois NumPy Arrays unidimensionais de tamanho 8: um formado apenas por 1's e outro formado por números aleatórios entre 0 e 9. Some estes dois NumPy Arrays e guarde o resultado dentro de um terceiro NumPy Array. Por fim, faça o seguinte:

- Se a soma de todos os elementos do Array resultante for >= 0, remodele este NumPy Array para se tornar uma matriz com mais linhas do que colunas. Senão, remodele para que se torne uma matriz com mais colunas do que linhas.

In [1]:
import numpy as np

ones_array = np.ones(8, dtype=int)
random_array = np.random.randint(0, 10, 8)
result_array = ones_array + random_array

print('Array de 1s:      ', ones_array)
print('Array aleatório:  ', random_array)
print('Array resultante: ', result_array)

total = result_array.sum()
print('\nSoma de todos os elementos:', total)

if total >= 0:
    reshaped = result_array.reshape(4, 2)
    print('\nSoma >= 0, então a matriz tem mais linhas do que colunas (4x2):')
else:
    reshaped = result_array.reshape(2, 4)
    print('\nSoma < 0, então a matriz tem mais colunas do que linhas (2x4):')

print(reshaped)

Array de 1s:       [1 1 1 1 1 1 1 1]
Array aleatório:   [9 2 7 0 8 5 2 2]
Array resultante:  [10  3  8  1  9  6  3  3]

Soma de todos os elementos: 43

Soma >= 0, então a matriz tem mais linhas do que colunas (4x2):
[[10  3]
 [ 8  1]
 [ 9  6]
 [ 3  3]]


## Questão 2

Mini Campo Minado:

- Crie um NumPy Array 2x2 formado apenas por 0's;
- Em seguida, adicione um número 1 em uma posição aleatória desta matriz;
- Faça uma entrada de dados para solicitar ao usuário que faça uma jogada (selecione uma posição da matriz):
  - Se ele selecionar todas as posições em que o número 1 não se encontra, mostre a mensagem "Congratulations! You beat the game! :)";
  - Senão, se dentro das 3 primeiras jogadas ele achar o número 1, mostre a mensagem "Game Over! :( Try Again!".

In [3]:
import numpy as np

field = np.zeros((2, 2), dtype=int)

mine_row = np.random.randint(0, 2)
mine_column = np.random.randint(0, 2)
field[mine_row, mine_column] = 1

chosen_positions = set()
safe_plays = 0

for play in range(1, 4):
    row = int(input(f'Jogada {play} - digite a linha [0/1]: '))
    column = int(input(f'Jogada {play} - digite a coluna [0/1]: '))

    while row not in (0, 1) or column not in (0, 1) or (row, column) in chosen_positions:
        print('Posição inválida ou já escolhida! Tente outra.')
        row = int(input(f'Jogada {play} - digite a linha [0/1]: '))
        column = int(input(f'Jogada {play} - digite a coluna [0/1]: '))

    chosen_positions.add((row, column))

    if field[row, column] == 1:
        print('\nGame Over! :( Try Again!')
        break

    safe_plays += 1
    print(f'Posição livre! Você já achou {safe_plays} de 3 posições seguras.')
else:
    print('\nCongratulations! You beat the game! :)')

print('\nO campo minado era:')
print(field)

Posição livre! Você já achou 1 de 3 posições seguras.
Posição inválida ou já escolhida! Tente outra.

Game Over! :( Try Again!

O campo minado era:
[[0 0]
 [0 1]]


## Questão 3

Crie uma matriz de tamanho qualquer. Extraia seu número de linhas e colunas, multiplique-os, e diga se esta matriz poderia se tornar um vetor unidimensional com número par ou ímpar de elementos.

In [4]:
import numpy as np

matrix = np.random.randint(1, 100, (3, 5))

print('Matriz gerada:')
print(matrix)

rows, columns = matrix.shape
total_elements = rows * columns

print('\nNúmero de linhas:', rows)
print('Número de colunas:', columns)
print('Linhas x colunas:', total_elements)

vector = matrix.reshape(total_elements)
print('\nComo vetor unidimensional:')
print(vector)

if total_elements % 2 == 0:
    print(f'\nEste vetor teria {total_elements} elementos, um número PAR de elementos.')
else:
    print(f'\nEste vetor teria {total_elements} elementos, um número ÍMPAR de elementos.')

Matriz gerada:
[[87 84 90 68 98]
 [15 38 58 22 17]
 [45 91 34 33 52]]

Número de linhas: 3
Número de colunas: 5
Linhas x colunas: 15

Como vetor unidimensional:
[87 84 90 68 98 15 38 58 22 17 45 91 34 33 52]

Este vetor teria 15 elementos, um número ÍMPAR de elementos.


## Questão 4

Crie uma matriz de tamanho 4x4 formada por números aleatórios inteiros entre 1 e 10 (use seed = 10). Em seguida:

- Mostre o resultado da média de cada linha e cada coluna da matriz gerada;
- Apresente o maior valor das médias das linhas e também das colunas;
- Mostre a quantidade de aparições de cada um dos números gerados na matriz. Em seguida, mostre apenas os números que aparecem 2 vezes.

In [5]:
import numpy as np

np.random.seed(10)
matrix = np.random.randint(1, 11, (4, 4))

print('Matriz gerada:')
print(matrix)

row_means = matrix.mean(axis=1)
column_means = matrix.mean(axis=0)

print('\nMédia de cada linha: ', row_means)
print('Média de cada coluna:', column_means)

print('\nMaior média entre as linhas: ', row_means.max())
print('Maior média entre as colunas:', column_means.max())

values, counts = np.unique(matrix, return_counts=True)

print('\nQuantidade de aparições de cada número:')
for value, count in zip(values, counts):
    print(f'O número {value} aparece {count} vez(es)')

twice = values[counts == 2]
print('\nNúmeros que aparecem exatamente 2 vezes:', twice)

Matriz gerada:
[[10  5  1  2]
 [10  1  2  9]
 [10  1  9  7]
 [ 5  4  1  5]]

Média de cada linha:  [4.5  5.5  6.75 3.75]
Média de cada coluna: [8.75 2.75 3.25 5.75]

Maior média entre as linhas:  6.75
Maior média entre as colunas: 8.75

Quantidade de aparições de cada número:
O número 1 aparece 4 vez(es)
O número 2 aparece 2 vez(es)
O número 4 aparece 1 vez(es)
O número 5 aparece 3 vez(es)
O número 7 aparece 1 vez(es)
O número 9 aparece 2 vez(es)
O número 10 aparece 3 vez(es)

Números que aparecem exatamente 2 vezes: [2 9]


## Questão 5

Crie uma matriz de tamanho 3x3 formada apenas por zeros e outra também de tamanho 3x3 formada apenas por uns. Some as duas matrizes elemento a elemento e multiplique o resultado por um escalar de sua escolha. Por fim, remodele (reshape) a matriz resultante para se tornar um vetor unidimensional de 9 elementos.

In [6]:
import numpy as np

zeros_matrix = np.zeros((3, 3), dtype=int)
ones_matrix = np.ones((3, 3), dtype=int)

print('Matriz de zeros:')
print(zeros_matrix)
print('\nMatriz de uns:')
print(ones_matrix)

added_matrix = zeros_matrix + ones_matrix
print('\nSoma elemento a elemento:')
print(added_matrix)

scalar = 7
multiplied_matrix = added_matrix * scalar
print(f'\nResultado multiplicado pelo escalar {scalar}:')
print(multiplied_matrix)

vector = multiplied_matrix.reshape(9)
print('\nMatriz remodelada como vetor de 9 elementos:')
print(vector)

Matriz de zeros:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Matriz de uns:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Soma elemento a elemento:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Resultado multiplicado pelo escalar 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Matriz remodelada como vetor de 9 elementos:
[7 7 7 7 7 7 7 7 7]


## Questão 6

Crie um NumPy Array unidimensional com os números de 10 a 30, espaçados de 2 em 2, usando arange. Mostre o maior valor do array e seu índice, o menor valor e seu índice, e a soma de todos os elementos.

In [7]:
import numpy as np

array = np.arange(10, 31, 2)

print('Array:', array)
print('Quantidade de elementos:', array.size)

print(f'\nMaior valor: {array.max()} (índice {array.argmax()})')
print(f'Menor valor: {array.min()} (índice {array.argmin()})')
print('Soma de todos os elementos:', array.sum())

Array: [10 12 14 16 18 20 22 24 26 28 30]
Quantidade de elementos: 11

Maior valor: 30 (índice 10)
Menor valor: 10 (índice 0)
Soma de todos os elementos: 220


## Questão 7

Crie dois NumPy Arrays unidimensionais de tamanho 5 com números aleatórios entre 1 e 10 (use seed = 7). Concatene os dois arrays em um terceiro, e transforme-o em uma matriz com 2 linhas e 5 colunas.

In [8]:
import numpy as np

np.random.seed(7)
first_array = np.random.randint(1, 11, 5)
second_array = np.random.randint(1, 11, 5)

print('Primeiro array:', first_array)
print('Segundo array: ', second_array)

concatenated = np.concatenate((first_array, second_array))
print('Concatenados:  ', concatenated)

matrix = concatenated.reshape(2, 5)
print('\nComo matriz de 2 linhas e 5 colunas:')
print(matrix)

Primeiro array: [ 5 10  7  4  4]
Segundo array:  [ 8  8 10  8  9]
Concatenados:   [ 5 10  7  4  4  8  8 10  8  9]

Como matriz de 2 linhas e 5 colunas:
[[ 5 10  7  4  4]
 [ 8  8 10  8  9]]
